version: "3.9"
services:
  gsl-mysql:
    container_name: gsl-database
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"