CREATE DATABASE IF NOT EXISTS pedido;
CREATE DATABASE IF NOT EXISTS cliente;
CREATE DATABASE IF NOT EXISTS deposito;
CREATE DATABASE IF NOT EXISTS parceiro;
CREATE DATABASE IF NOT EXISTS entrega;
CREATE DATABASE IF NOT EXISTS sge;

USE sge;

CREATE TABLE pedido_criado (
	id INT AUTO_INCREMENT,
	codigo VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE pedido_entregue (
	id INT AUTO_INCREMENT,
	codigo VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
);