spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - TokenRelay
      routes:
        - id: parceiro
          uri: http://localhost:8082/api/parceiros
          predicates:
            - Path=/api/parceiros/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: documentacao-api
          uri: http://localhost:8083/documentacao-api
          predicates:
            - Path=/documentacao-api/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: frete
          uri: http://localhost:8085/api/fretes
          predicates:
            - Path=/api/fretes/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: cliente
          uri: http://localhost:8086/api/clientes
          predicates:
            - Path=/api/clientes/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: pedido
          uri: http://localhost:8087/api/pedidos
          predicates:
            - Path=/api/pedidos/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: deposito
          uri: http://localhost:8088/api/depositos
          predicates:
            - Path=/api/depositos/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: entrega
          uri: http://localhost:8089/api/entregas
          predicates:
            - Path=/api/entregas/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: middleware-sge
          uri: http://localhost:8090/api/middleware-sge
          predicates:
            - Path=/api/middleware-sge/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          gsl-gateway:
            client-id: gateway
            client-secret: ih8Ba8aJfD6QJdESHAep3BOiwSBTZKgB
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          gsl-gateway:
            authorization-uri: http://localhost:9000/auth/realms/SistemaGSL/protocol/openid-connect/auth
            token-uri: http://localhost:9000/auth/realms/SistemaGSL/protocol/openid-connect/token
            userinfo-uri: http://localhost:9000/auth/realms/SistemaGSL/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username