server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: "@currentProfile@"
logging.level:
  org.springframework: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"