openapi: 3.0.1
info:
  title: Clientes API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/clientes
    description: localhost - gateway
paths:
  /{id}/fretes/calcular:
    post:
      tags:
        - cálculo frete
      summary: Calcula custo do frete
      operationId: calcularFrete
      parameters:
        - name: id
          in: path
          description: Id do cliente
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormCalcularFreteDTO'
        required: true
      responses:
        200:
          description: Custo do frete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustoFreteDTO'
  /{id}/pedidos:
    post:
      tags:
        - pedidos
      summary: Cria um pedido para o cliente
      operationId: criarPedido
      parameters:
        - name: id
          in: path
          description: Id do cliente
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormCriarPedidoDTO'
        required: true
      responses:
        201:
          description: Pedido criado
  /{id}/enderecos:
    get:
      tags:
        - endereços
      summary: Busca endereços do cliente
      operationId: buscarEnderecosDoCliente
      parameters:
        - name: id
          in: path
          description: Id do cliente
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Endereços do cliente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnderecoDTO'
components:
  schemas:
    FormCalcularFreteDTO:
      type: object
      properties:
        cepOrigem:
          type: integer
          format: int32
          example: 123
        cepDestino:
          type: integer
          format: int32
          example: 456
        volumes:
          type: array
          items:
            $ref: '#/components/schemas/FormVolumeDTO'
        servicosOpcionais:
          type: array
          items:
            $ref: '#/components/schemas/FormServicoOpcionalDTO'
    CustoFreteDTO:
        type: object
        properties:
          prazoDiasUteis:
            type: integer
            format: int32
            example: 10
          custoTotal:
            type: number
            format: double
            example: 10
          custoFrete:
            type: number
            format: double
            example: 10
          custoServicos:
            type: number
            format: double
            example: 5
          descontoCliente:
            type: number
            format: double
            example: 5
    FormVolumeDTO:
        type: object
        properties:
          formato:
            type: string
            enum:
              - CAIXA
              - ENVELOPE
          peso:
            type: number
            format: double
            example: 10
          unidadeMedidaPeso:
            type: string
            enum:
              - KG
              - G
          altura:
            type: number
            format: double
            example: 50
          largura:
            type: number
            format: double
            example: 50
          comprimento:
            type: number
            format: double
            example: 50
          quantidade:
            type: integer
            format: int32
            example: 1
    FormServicoOpcionalDTO:
      type: object
      properties:
        tipo:
          type: string
          enum:
            - SEGURO
        parametros:
          type: object
          example:
            valorDeclarado: 150
    FormCriarPedidoDTO:
      type: object
      properties:
        enderecoId:
          type: integer
          format: int2
          example: 1
        nomeDestinatario:
          type: string
          example: Nome destinatário
        documentoDestinatario:
          type: string
          example: 23.405.170/0001-51
        enderecoDestinatario:
          $ref: '#/components/schemas/FormEnderecoDTO'
        volumes:
          type: array
          items:
            $ref: '#/components/schemas/FormVolumeDTO'
        servicosOpcionais:
          type: array
          items:
            $ref: '#/components/schemas/FormServicoOpcionalDTO'
    FormEnderecoDTO:
      type: object
      properties:
        endereco:
          type: string
          example: Rua XYZ
        cidade:
          type: string
          example: Chapecó
        estado:
          type: string
          example: SC
        cep:
          type: integer
          format: int32
          example: 89801000
        complemento:
          type: string
          example: Complemento XYZ
        contato:
          type: string
          example: 49 9 0000-1111
        clienteId:
          type: integer
          format: int64
          example: 1
    EnderecoDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        endereco:
          type: string
          example: Rua XYZ
        cidade:
          type: string
          example: Chapecó
        estado:
          type: string
          example: SC
        cep:
          type: integer
          format: int32
          example: 89801000
        complemento:
          type: string
          example: Complemento XYZ
        contato:
          type: string
          example: 49 9 0000-1111
        clienteId:
          type: integer
          format: int64
          example: 1